name:                zloysql
version:             0.1.0.0
github:              "zloylesnoy/zloysql"
license:             MIT
author:              "Alexey Drozdov"
maintainer:          "zloylesnoy@gmail.com"
copyright:           "2018 Alexey Drozdov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/zloylesnoy/zloysql#readme>

dependencies:
- base >= 4.7 && < 5
- regex-posix
- containers
- MissingH
- scientific

library:
  source-dirs:
      - sch
      - gen

executables:
  zloysql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zloysql

tests:
  zloysql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zloysql
